export const NEIGHBOURS = {
    "Afghanistan": ['Middle East', 'Ukraine', 'Ural', 'China', 'India'],
    "Alaska": ['Northwest Territory', 'Alberta', 'Kamchatka'],
    "Alberta": ['Alaska', 'Northwest Territory', 'Ontario', 'Western United States'],
    "Argentina": ['Peru', 'Brazil'],
    "Brazil": ['Venezuela', 'Peru', 'Argentina', 'North Africa'],
    "Central America": ['Western United States', 'Eastern United States', 'Venezuela'],
    "China": ['Siam', 'India', 'Afghanistan', 'Ural', 'Siberia', 'Mongolia'],
    "Congo": ['North Africa', 'East Africa', 'South Africa'],
    "East Africa": ['Egypt', 'North Africa', 'Congo', 'South Africa', 'Madagascar', 'Middle East'],
    "Eastern Australia": ['New Guinea', 'Western Australia'],
    "Eastern United States": ['Ontario', 'Quebec', 'Western United States', 'Central America'],
    "Egypt": ['Southern Europe', 'East Africa', 'North Africa', 'Middle East'],
    "Great Britain": ['Iceland', 'Scandenavia', 'Northern Europe', 'Western Europe'],
    "Greenland": ['Northwest Territory', 'Ontario', 'Quebec', 'Iceland'],
    "Iceland": ['Greenland', 'Scandenavia', 'Great Britain'],
    "India": ['Middle East', 'Afghanistan', 'China', 'Siam'],
    "Indonesia": ['Siam', 'New Guinea', 'Western Australia'],
    "Irkutsk": ['Yakutsk', 'Kamchatka', 'Mongolia', 'Siberia'],
    "Japan": ['Kamchatka', 'Mongolia'],
    "Kamchatka": ['Yakutsk', 'Irkutsk', 'Mongolia', 'Japan', 'Alaska'],
    "Madagascar": ['East Africa', 'South Africa'],
    "Middle East": ['Southern Europe', 'Ukraine', 'Afghanistan', 'India', 'Egypt', 'East Africa'],
    "Mongolia": ['Japan', 'Kamchatka', 'Irkutsk', 'Siberia', 'China'],
    "New Guinea": ['Indonesia', 'Western Australia', 'Eastern Australia'],
    "North Africa": ['Western Europe', 'Southern Europe', 'Egypt', 'East Africa', 'Congo', 'Brazil'],
    "Northern Europe": ['Scandenavia', 'Great Britain', 'Ukraine', 'Southern Europe', 'Western Europe'],
    "Northwest Territory": ['Alaska', 'Alberta', 'Ontario', 'Greenland'],
    "Ontario": ['Northwest Territory', 'Greenland', 'Quebec', 'Eastern United States', 'Western United States', 'Alberta'],
    "Peru": ['Venezuela', 'Brazil', 'Argentina'],
    "Quebec": ['Greenland', 'Ontario', 'Eastern United States'],
    "Scandenavia": ['Iceland', 'Great Britain', 'Northern Europe', 'Ukraine'],
    "Siam": ['India', 'China', 'Indonesia'],
    "Siberia": ['Ural', 'China', 'Mongolia', 'Yakutsk', 'Irkutsk'],
    "South Africa": ['Congo', 'East Africa', 'Madagascar'],
    "Southern Europe": ['Western Europe', 'Northern Europe', 'Ukraine', 'North Africa', 'Egypt', 'Middle East'],
    "Ukraine": ['Scandenavia', 'Northern Europe', 'Southern Europe', 'Middle East', 'Afghanistan', 'Ural'],
    "Ural": ['Ukraine', 'Siberia', 'China', 'Afghanistan'],
    "Venezuela": ['Central America', 'Peru', 'Brazil'],
    "Western Australia": ['Indonesia', 'New Guinea', 'Eastern Australia'],
    "Western Europe": ['Great Britain', 'Northern Europe', 'Southern Europe', 'North Africa'],
    "Western United States": ['Alberta', 'Ontario', 'Eastern United States', 'Central America'],
    "Yakutsk": ['Siberia', 'Irkutsk', 'Kamchatka'],
};
