
name: Continuous Integration

on:
  push: { "branches": [ "master" ] } 

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🧰 Setup Stack
      uses: mstksg/setup-stack@v1

    - name: 🔨 Build & Test
      run: |
        # Stack does all sort of exotic manipulations in the terminal with the build output. This
        # can be the source of unexpected issues in emulated terminals, hence `--no-terminal`.
        stack --no-terminal test 
